### ISSUE TITLE
Support URL locations for APK files

### ISSUE THREAD

**Issue by sdlaver** [solana-mobile/dapp-publishing#191] opened 2023-03-30 20:08 UTC
This allows external hosting providers other than arweave to be used. Currently, specifying a non-local APK path gives an error, `Invalid path to APK file`.

Note that this will require fetching APKs for local processing.

**Comment by creativedrewy** [comment] 2023-04-28 23:48
Duplicate of #158

**Closed** 2023-04-28 23:49 UTC
Labels: enhancement
